input_file: ../../Downloads/Beginners Handwriting practice _ Learn Cursive writing _ Palash Calligraphy.mp4
# input_file: ../../Downloads/Beautiful calligraphy writing _ neat handwriting with calligraphy pen.mp4
output_folder: "./ss"
color: [0, 0, 0]
step: 0.2
show_by: "mask"  # or "frame"
use_binary_mask: true
take_ss: true
annoted_data_folder_path: ~/Downloads/Noise labeling in Hand writing.v1i.coco-segmentation