path: ../../Downloads/yolov8/yolov8 #create a softlink for the Download folder
train: train/images
val: valid/images
test: test/images

nc: 4
names: ['hand', 'noise', 'not-noise', 'page-marker']

roboflow:
  workspace: mohit-xb7ag
  project: noise-labeling-in-hand-writing
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/mohit-xb7ag/noise-labeling-in-hand-writing/dataset/2
